# Generated by Django 6.0 on 2026-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stanok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='Seriya raqami')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joylashuv')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('repair', "Ta'mirda"), ('inactive', 'Faol emas')], default='active', max_length=20, verbose_name='Holat')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stanok',
                'verbose_name_plural': 'Stanoklar',
                'ordering': ['name'],
            },
        ),
    ]
