# Generated by Django 6.0 on 2026-04-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanok',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stanok',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stanok',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stanok',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='stanok',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='stanok',
            name='updated_at',
        ),
    ]
