# Generated by Django 6.0 on 2026-04-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_remove_stanok_created_at_remove_stanok_description_and_more'),
        ('order', '0009_brujka_order_brujka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomMahsulotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(verbose_name='Miqdor (dona)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hom_loglar', to='order.order', verbose_name='Buyurtma')),
                ('stanok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hom_loglar', to='casting.stanok', verbose_name='Stanok')),
            ],
            options={
                'verbose_name': 'Hom mahsulot log',
                'verbose_name_plural': 'Hom mahsulot loglar',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TayorMahsulotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(verbose_name='Miqdor (dona)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tayor_loglar', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Tayor mahsulot log',
                'verbose_name_plural': 'Tayor mahsulot loglar',
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
