# Generated by Django 6.0 on 2026-04-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_hommahsulotlog_tayormahsulotlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(default='kg', help_text='kg, litr, dona va h.k.', max_length=30, verbose_name="O'lchov birligi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zamak',
                'verbose_name_plural': 'Zamaklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Raqam')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('deadline', models.DateField(verbose_name='Muddat')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_process', 'Ishlab chiqarilmoqda'), ('done', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': "Qo'shimcha buyurtma",
                'verbose_name_plural': "Qo'shimcha buyurtmalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalHomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(verbose_name='Miqdor (dona)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('stanok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_hom_loglar', to='casting.stanok', verbose_name='Stanok')),
                ('add_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hom_loglar', to='casting.additionalorder', verbose_name="Qo'shimcha buyurtma")),
            ],
            options={
                'verbose_name': "Qo'shimcha hom log",
                'verbose_name_plural': "Qo'shimcha hom loglar",
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RasxodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('stanok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasxodlar', to='casting.stanok', verbose_name='Stanok')),
                ('zamak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rasxodlar', to='casting.zamak', verbose_name='Zamak')),
            ],
            options={
                'verbose_name': 'Rasxod',
                'verbose_name_plural': 'Rasxodlar',
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
