# Generated by Django 6.0 on 2026-04-24 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_zamak_additionalorder_additionalhomlog_rasxodlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTayorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(verbose_name='Miqdor (dona)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tayor_loglar', to='casting.additionalorder', verbose_name="Qo'shimcha buyurtma")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
            ],
            options={
                'verbose_name': "Qo'shimcha tayor log",
                'verbose_name_plural': "Qo'shimcha tayor loglar",
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
