# Generated by Django 6.0 on 2026-04-25 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0006_atxotrasxod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyishRasxod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300, verbose_name='Nomi')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
            ],
            options={
                'verbose_name': 'Quyish rasxodi',
                'verbose_name_plural': 'Quyish rasxodlari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AtxotRasxod',
        ),
    ]
