# Generated by Django 6.0 on 2026-04-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0007_quyishrasxod_delete_atxotrasxod'),
        ('order', '0009_brujka_order_brujka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyishJarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quyilmoqda', 'Quyilmoqda'), ('quyib_bolindi', "Quyib bo'lindi"), ('quyilmadi', 'Quyilmadi')], default='quyilmoqda', max_length=20, verbose_name='Quyish holati')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh / sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quyish_jarayonlar', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quyish_jarayon', to='order.order', verbose_name='Buyurtma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quyish_jarayon_updates', to=settings.AUTH_USER_MODEL, verbose_name="Oxirgi o'zgartirgan")),
            ],
            options={
                'verbose_name': 'Quyish jarayoni',
                'verbose_name_plural': 'Quyish jarayonlari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
