# Generated by Django 6.0 on 2026-04-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0008_quyishjarayon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuyishJarayon',
        ),
    ]
