# Generated by Django 6.0 on 2026-04-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0010_quyishjarayon_quyishjarayonlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TayorMahsulotLog',
        ),
    ]
