# Generated by Django 6.0 on 2026-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0011_remove_tayormahsulotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hommahsulotlog',
            name='smena',
            field=models.CharField(choices=[('kun', 'Kunduzgi smena'), ('tun', 'Tungi smena')], default='kun', max_length=10, verbose_name='Smena'),
        ),
    ]
