# Generated by Django 6.0 on 2026-04-29 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0009_brujka_order_brujka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_yaratganlar', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Tosh',
                'verbose_name_plural': 'Toshlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToshQadashJarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('qabul_qilindi', 'Qabul qilindi'), ('tosh_qadalmoqda', 'Tosh qadalmoqda'), ('tosh_qadaldi', 'Tosh qadaldi'), ('tosh_qadalmadi', 'Tosh qadalmadi')], default='qabul_qilindi', max_length=20, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh / sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_jarayonlar', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tosh_jarayon', to='order.order', verbose_name='Buyurtma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_jarayon_updates', to=settings.AUTH_USER_MODEL, verbose_name="Oxirgi o'zgartirgan")),
            ],
            options={
                'verbose_name': 'Tosh qadash jarayoni',
                'verbose_name_plural': 'Tosh qadash jarayonlari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QabulJarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('ilinmoqda', 'Ilinmoqda'), ('ilib_bolindi', "Ilib bo'lindi"), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_jarayon_updates', to=settings.AUTH_USER_MODEL, verbose_name="Oxirgi o'zgartirgan")),
                ('tosh_jarayon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_jarayon', to='tosh.toshqadashjarayon', verbose_name='Tosh qadash jarayoni')),
            ],
            options={
                'verbose_name': 'Qabul jarayoni',
                'verbose_name_plural': 'Qabul jarayonlari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KleyRasxod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smena', models.CharField(choices=[('kun', 'Kunduzgi smena'), ('tun', 'Tungi smena')], default='kun', max_length=5, verbose_name='Smena')),
                ('kley_gramm', models.DecimalField(decimal_places=2, help_text='Nechi gramm kley ketdi', max_digits=10, verbose_name='Kley (gramm)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kley_rasxodlar', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kley_rasxodlar', to='tosh.toshqadashjarayon', verbose_name='Tosh qadash jarayoni')),
            ],
            options={
                'verbose_name': 'Kley rasxodi',
                'verbose_name_plural': 'Kley rasxodlari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToshQadashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smena', models.CharField(choices=[('kun', 'Kunduzgi smena'), ('tun', 'Tungi smena')], default='kun', max_length=5, verbose_name='Smena')),
                ('par_soni', models.PositiveIntegerField(default=1, verbose_name='Par soni')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_log_yozuvlar', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('hodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_loglar', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='tosh.toshqadashjarayon', verbose_name='Tosh qadash jarayoni')),
                ('tosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loglar', to='tosh.tosh', verbose_name='Tosh')),
            ],
            options={
                'verbose_name': 'Tosh qadash log',
                'verbose_name_plural': 'Tosh qadash loglar',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToshRasxod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smena', models.CharField(choices=[('kun', 'Kunduzgi smena'), ('tun', 'Tungi smena')], default='kun', max_length=5, verbose_name='Smena')),
                ('tosh_gramm', models.DecimalField(decimal_places=2, help_text='Nechi gramm tosh sarflandi', max_digits=10, verbose_name='Tosh (gramm)')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tosh_rasxod_yozuvlar', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tosh_rasxodlar', to='tosh.toshqadashjarayon', verbose_name='Tosh qadash jarayoni')),
                ('tosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rasxodlar', to='tosh.tosh', verbose_name='Tosh')),
            ],
            options={
                'verbose_name': 'Tosh rasxodi',
                'verbose_name_plural': 'Tosh rasxodlari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
