# Generated by Django 6.0 on 2026-04-21 07:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('bonus_type', models.CharField(choices=[('bonus', 'Mukofot'), ('kpi', 'KPI'), ('penalty', 'Jarima'), ('other', 'Boshqa')], default='bonus', max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Miqdor (so'm)")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Bonus/KPI',
                'verbose_name_plural': 'Bonus/KPI',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Soatlik stavka (so'm)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_settings', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Oylik sozlamalari',
                'verbose_name_plural': 'Oylik sozlamalari',
            },
        ),
    ]
