from apps.order.views.order_views import *
from apps.order.views.casting_views import *
from apps.order.views.montaj_views import *
from apps.order.views.hanging_views import *
from apps.order.views.stone_views import *
from apps.order.views.packaging_views import *
from apps.order.views.warehouse_views import *
from apps.order.views.outsource_views import *
from apps.order.views.quality_views import *
