# Generated by Django 6.0 on 2026-04-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_name_alter_shift_name_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='ceo',
        ),
    ]
