# Generated by Django 6.0 on 2026-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_branch_ceo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.shift', verbose_name='Smenalar'),
        ),
    ]
