# Generated by Django 6.0 on 2026-04-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_shift_user_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shifts',
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.shift', verbose_name='Smena'),
        ),
    ]
