# Generated by Django 6.0 on 2026-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_shifts_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, help_text="VIP hodim kunduzgi yoki kechki smenada ishlashi mumkin. Kelgan vaqtiga qarab smena aniqlanadi va o'sha smenaning to'liq soati maoshga qo'shiladi (kech kelsa ham to'liq smena oyligi beriladi).", verbose_name='VIP hodim'),
        ),
    ]
