# Generated by Django 6.0 on 2026-04-21 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_is_vip_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.BooleanField(help_text='True=berildi, False=olindi', verbose_name='VIP holati')),
                ('effective_from', models.DateField(verbose_name='Amal qilish boshlanishi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_changes_made', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_history', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'VIP status tarixi',
                'verbose_name_plural': 'VIP status tarixi',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
