# Generated by Django 6.0 on 2026-04-17 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/%Y/%m/', verbose_name='Rasm')),
                ('deadline', models.DateField(verbose_name="Tayyor bo'lish sanasi")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('in_process', 'Ishlab chiqarilmoqda'), ('ready', 'Tayyor'), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('current_stage', models.CharField(blank=True, choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor')], max_length=20, verbose_name="Joriy bo'lim")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MontajStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Til qadashda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('assembled_quantity', models.PositiveIntegerField(default=0, verbose_name='Til qadalgan')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montaj_works', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='montaj', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Montaj bosqichi',
                'verbose_name_plural': 'Montaj bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='HangingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('hanging', 'Vishilkaga ilishda'), ('chemical_soak', "Himiyada bo'ktirishda"), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('hung_quantity', models.PositiveIntegerField(default=0, verbose_name='Ilingan')),
                ('soaked_quantity', models.PositiveIntegerField(default=0, verbose_name="Bo'ktirilgan")),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanging_works', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hanging', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Ilish bosqichi',
                'verbose_name_plural': 'Ilish bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='CastingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('separating', 'Ajratilmoqda'), ('washing', 'Yuvilmoqda'), ('chemical', 'Himiyaviy ishlov'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('separated_quantity', models.PositiveIntegerField(default=0, verbose_name='Ajratilgan')),
                ('washed_quantity', models.PositiveIntegerField(default=0, verbose_name='Yuvilgan')),
                ('chemical_quantity', models.PositiveIntegerField(default=0, verbose_name="Himiyadan o'tgan")),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_works', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casting', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Quyish bosqichi',
                'verbose_name_plural': 'Quyish bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='PackagingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Qadoqlanmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('packed_quantity', models.PositiveIntegerField(default=0, verbose_name='Qadoqlangan')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='order.order', verbose_name='Buyurtma')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_works', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Upakovka bosqichi',
                'verbose_name_plural': 'Upakovka bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor')], max_length=20, verbose_name='Bosqich')),
                ('result', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('passed', "O'tdi"), ('partial', "Qisman o'tdi"), ('failed', "O'tmadi")], default='pending', max_length=20, verbose_name='Natija')),
                ('checked_quantity', models.PositiveIntegerField(default=0, verbose_name='Tekshirilgan')),
                ('passed_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqli')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('defect_reason', models.TextField(blank=True, verbose_name='Nuqson sababi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Nazoratchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Sifat nazorati',
                'verbose_name_plural': 'Sifat nazorati',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoneSettingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Tosh qadashda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('stones_set_quantity', models.PositiveIntegerField(default=0, verbose_name='Tosh qadalgan')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stone_setting', to='order.order', verbose_name='Buyurtma')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stone_setting_works', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Tosh qadash bosqichi',
                'verbose_name_plural': 'Tosh qadash bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('received', 'Qabul qilindi'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Haridorga topshirildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Qabul qilingan')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='Yetkazilgan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='order.order', verbose_name='Buyurtma')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_receives', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Ombor',
            },
        ),
    ]
