# Generated by Django 6.0 on 2026-04-17 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor'), ('outsource', 'Tashqi ishlov')], max_length=20, verbose_name="Joriy bo'lim"),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='stage',
            field=models.CharField(choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor'), ('outsource', 'Tashqi ishlov')], max_length=20, verbose_name='Bosqich'),
        ),
        migrations.CreateModel(
            name='OutsourceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('in_process', 'Bajarilmoqda'), ('received', 'Qaytib keldi'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('work_description', models.TextField(verbose_name='Bajariladigan ish tavsifi')),
                ('contractor', models.CharField(max_length=255, verbose_name='Pudratchi (tashqi ustaxona)')),
                ('contractor_phone', models.CharField(blank=True, max_length=20, verbose_name='Pudratchi telefoni')),
                ('sent_quantity', models.PositiveIntegerField(default=0, verbose_name='Yuborilgan miqdor')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Qaytib kelgan')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('return_to_stage', models.CharField(choices=[('casting', "Quyish bo'limiga"), ('montaj', "Montaj bo'limiga"), ('hanging', "Ilish bo'limiga"), ('stone_setting', "Tosh qadash bo'limiga"), ('packaging', "Upakovka bo'limiga")], help_text="Tashqi ishlov tugagach qaysi bo'limga qaytadi", max_length=20, verbose_name='Qaytish bosqichi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytib kelgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsource_works', to='order.order', verbose_name='Buyurtma')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsource_sent', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Tashqi ishlov',
                'verbose_name_plural': 'Tashqi ishlovlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
