# Generated by Django 6.0 on 2026-04-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_current_stage_alter_qualitycontrol_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingstage',
            name='chemical_quantity',
        ),
        migrations.RemoveField(
            model_name='castingstage',
            name='separated_quantity',
        ),
        migrations.RemoveField(
            model_name='castingstage',
            name='washed_quantity',
        ),
        migrations.RemoveField(
            model_name='castingstage',
            name='worker',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='castingstage',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Quyilmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='OrderStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor'), ('outsource', 'Tashqi ishlov')], max_length=20, verbose_name='Bosqich')),
                ('from_department', models.CharField(blank=True, max_length=50, verbose_name="Qaysi bo'limdan")),
                ('to_department', models.CharField(max_length=50, verbose_name="Qaysi bo'limga")),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_accepted_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='order.order')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bosqich harakati',
                'verbose_name_plural': 'Bosqich harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
