# Generated by Django 6.0 on 2026-04-22 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_castingstage_chemical_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor')], max_length=20, verbose_name="Qaysi bo'limdan")),
                ('to_stage', models.CharField(choices=[('casting', "Quyish bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi"), ('stone_setting', "Tosh qadash bo'limi"), ('packaging', "Upakovka bo'limi"), ('warehouse', 'Ombor')], max_length=20, verbose_name="Qaysi bo'limga")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('sent_quantity', models.PositiveIntegerField(verbose_name='Yuborilgan miqdor')),
                ('accepted_quantity', models.PositiveIntegerField(default=0, verbose_name='Qabul qilingan miqdor')),
                ('rejected_quantity', models.PositiveIntegerField(default=0, verbose_name='Rad etilgan miqdor')),
                ('note', models.TextField(blank=True, verbose_name='Izoh (yuboruvchi)')),
                ('accept_note', models.TextField(blank=True, verbose_name='Izoh (qabul qiluvchi)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_accepted', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='order.order', verbose_name='Buyurtma')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_sent', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': "Bo'limlar arasi transfer",
                'verbose_name_plural': "Bo'limlar arasi transferlar",
                'ordering': ['-sent_at'],
            },
        ),
    ]
