# Generated by Django 6.0 on 2026-04-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_stagetransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Stanok nomi')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stanok',
                'verbose_name_plural': 'Stanoklar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orderstagelog',
            name='stanok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_logs', to='order.stanok', verbose_name='Stanok'),
        ),
    ]
