# Generated by Django 6.0 on 2026-04-22 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_stanok_orderstagelog_stanok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coating_type',
            field=models.CharField(choices=[('spray_only', 'Faqat sepish'), ('paint_only', "Faqat bo'yash"), ('spray_and_paint', "Sepish va bo'yash")], default='spray_only', max_length=20, verbose_name='Qoplama turi'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_assembly',
            field=models.BooleanField(default=False, verbose_name='Montaj bormi'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_stone',
            field=models.BooleanField(default=False, verbose_name='Tosh qadash bormi'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Past'), ('normal', 'Oddiy'), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=10, verbose_name='Muhimlik darajasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('casting', "Quyish bo'limi"), ('attach', "Ilish bo'limi"), ('spray', "Sepish bo'limi"), ('paint', "Bo'yash bo'limi"), ('packaging', "Upakovka bo'limi"), ('stone', "Tosh qadash bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi (eski)"), ('stone_setting', "Tosh qadash bo'limi (eski)"), ('warehouse', 'Ombor'), ('outsource', 'Tashqi ishlov')], max_length=20, verbose_name="Joriy bo'lim"),
        ),
        migrations.AlterField(
            model_name='orderstagelog',
            name='stage',
            field=models.CharField(choices=[('casting', "Quyish bo'limi"), ('attach', "Ilish bo'limi"), ('spray', "Sepish bo'limi"), ('paint', "Bo'yash bo'limi"), ('packaging', "Upakovka bo'limi"), ('stone', "Tosh qadash bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi (eski)"), ('stone_setting', "Tosh qadash bo'limi (eski)"), ('warehouse', 'Ombor'), ('outsource', 'Tashqi ishlov')], max_length=20, verbose_name='Bosqich'),
        ),
        migrations.AlterField(
            model_name='stagetransfer',
            name='from_stage',
            field=models.CharField(choices=[('casting', "Quyish bo'limi"), ('attach', "Ilish bo'limi"), ('spray', "Sepish bo'limi"), ('paint', "Bo'yash bo'limi"), ('packaging', "Upakovka bo'limi"), ('stone', "Tosh qadash bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi (eski)"), ('stone_setting', "Tosh qadash bo'limi (eski)"), ('warehouse', 'Ombor')], max_length=20, verbose_name="Qaysi bo'limdan"),
        ),
        migrations.AlterField(
            model_name='stagetransfer',
            name='to_stage',
            field=models.CharField(choices=[('casting', "Quyish bo'limi"), ('attach', "Ilish bo'limi"), ('spray', "Sepish bo'limi"), ('paint', "Bo'yash bo'limi"), ('packaging', "Upakovka bo'limi"), ('stone', "Tosh qadash bo'limi"), ('montaj', "Montaj bo'limi"), ('hanging', "Ilish bo'limi (eski)"), ('stone_setting', "Tosh qadash bo'limi (eski)"), ('warehouse', 'Ombor')], max_length=20, verbose_name="Qaysi bo'limga"),
        ),
        migrations.CreateModel(
            name='AssemblyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Montajda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Montaj bosqichi',
                'verbose_name_plural': 'Montaj bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='AttachStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Ilinmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attach', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Ilish bosqichi',
                'verbose_name_plural': 'Ilish bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='PackStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Qadoqlanmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('packed_quantity', models.PositiveIntegerField(default=0, verbose_name='Qadoqlangan')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pack', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Upakovka bosqichi',
                'verbose_name_plural': 'Upakovka bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='PaintStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', "Bo'yalmoqda"), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('layer_number', models.PositiveSmallIntegerField(default=2, verbose_name='Qavat raqami')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paint', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "Bo'yash bosqichi",
                'verbose_name_plural': "Bo'yash bosqichlari",
            },
        ),
        migrations.CreateModel(
            name='SprayStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Sepilyapti'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('layer_number', models.PositiveSmallIntegerField(default=1, verbose_name='Qavat raqami')),
                ('layer_type', models.CharField(choices=[('spray', 'Sepish'), ('paint', "Bo'yash")], default='spray', max_length=10, verbose_name='Qavat turi')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spray', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Sepish bosqichi',
                'verbose_name_plural': 'Sepish bosqichlari',
            },
        ),
        migrations.CreateModel(
            name='StanokLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('defect', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('side', models.CharField(choices=[('top', 'Yuqori tomon'), ('bottom', 'Pastki tomon'), ('single', 'Bir tomonlama')], default='single', max_length=10, verbose_name='Tomoni')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanok_logs', to='order.order', verbose_name='Buyurtma')),
                ('stanok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='order.stanok', verbose_name='Stanok')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stanok_logs', to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Stanok logi',
                'verbose_name_plural': 'Stanok loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoneStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_process', 'Tosh qadashda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy miqdor')),
                ('defect_quantity', models.PositiveIntegerField(default=0, verbose_name='Yaroqsiz')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stone', to='order.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Tosh qadash bosqichi',
                'verbose_name_plural': 'Tosh qadash bosqichlari',
            },
        ),
    ]
