# Generated by Django 6.0 on 2026-04-23 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_coating_type_order_has_assembly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstagelog',
            name='stanok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_stage_logs', to='order.stanok', verbose_name='Stanok'),
        ),
        migrations.AlterField(
            model_name='orderstagelog',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_stage_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
