# Generated by Django 6.0 on 2026-04-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_attachstage_order_remove_castingstage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brujka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='brujka/%Y/%m/', verbose_name='Rasm')),
                ('color', models.CharField(default='#C0A060', max_length=7, verbose_name='Rang (hex)')),
                ('coating_type', models.CharField(choices=[('spray_only', 'Faqat sepish'), ('paint_only', "Faqat bo'yash"), ('spray_and_paint', "Sepish va bo'yash")], default='spray_only', max_length=20, verbose_name='Qoplama turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Brujka',
                'verbose_name_plural': 'Brujkalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='brujka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.brujka', verbose_name='Brujka'),
        ),
    ]
