# Generated by Django 6.0 on 2026-04-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_user_shift_user_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmadi'), ('half_day', 'Yarim kun')], default='present', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.branch', verbose_name='Filial')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='users.shift', verbose_name='Smena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-date', '-check_in'],
                'unique_together': {('user', 'shift', 'date')},
            },
        ),
    ]
