# Generated by Django 6.0 on 2026-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name="Qo'shimcha smena"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmadi'), ('half_day', 'Yarim kun'), ('early_leave', 'Erta ketdi')], default='present', max_length=20, verbose_name='Holat'),
        ),
    ]
