# Generated by Django 6.0 on 2026-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/%d/', verbose_name='Rasm'),
        ),
    ]
