# Generated by Django 6.0 on 2026-04-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_simplify_attendance'),
        ('users', '0005_remove_user_shifts_user_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='users.branch', verbose_name='Filial'),
        ),
    ]
