# Generated by Django 6.0 on 2026-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, help_text='Kiosk skanerlagan haqiqiy vaqt. check_out = hisobiy (smena end yoki haqiqiy).', null=True, verbose_name='Chiqish vaqti (haqiqiy)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='effective_check_in',
            field=models.DateTimeField(blank=True, help_text='Erta kelsa smena start_time, kechiksa/vaqtida check_in vaqti.', null=True, verbose_name='Kirish vaqti (hisob)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti (haqiqiy)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti (hisobiy)'),
        ),
    ]
