# Generated by Django 6.0 on 2026-04-27 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0009_brujka_order_brujka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vishilka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Nomi')),
                ('turi', models.CharField(choices=[('par_50', '50 parlik'), ('par_25', '25 parlik')], default='par_50', max_length=10, verbose_name='Vishilka turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vishilka',
                'verbose_name_plural': 'Vishilkalar',
                'ordering': ['turi', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='IlishJarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('qabul_qilindi', 'Qabul qilindi'), ('ilinmoqda', 'Ilinmoqda'), ('ilib_bolindi', "Ilib bo'lindi"), ('bekor_qilindi', 'Bekor qilindi')], default='qabul_qilindi', max_length=20, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh / sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilish_jarayonlar', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ilish_jarayon', to='order.order', verbose_name='Buyurtma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilish_jarayon_updates', to=settings.AUTH_USER_MODEL, verbose_name="Oxirgi o'zgartirgan")),
            ],
            options={
                'verbose_name': 'Ilish jarayoni',
                'verbose_name_plural': 'Ilish jarayonlari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IlishJarayonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smena', models.CharField(choices=[('kun', 'Kunduzgi smena'), ('tun', 'Tungi smena')], default='kun', max_length=5, verbose_name='Smena')),
                ('vishilka_soni', models.PositiveIntegerField(default=1, verbose_name='Vishilka soni')),
                ('natija', models.CharField(blank=True, choices=[('ilib_bolindi', "Ilib bo'lindi"), ('bekor_qilindi', 'Bekor qilindi')], max_length=20, null=True, verbose_name='Natija')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilish_log_yozuvlar', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
                ('hodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilish_loglar', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='ilish.ilishjarayon', verbose_name='Ilish jarayoni')),
                ('vishilka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loglar', to='ilish.vishilka', verbose_name='Vishilka')),
            ],
            options={
                'verbose_name': 'Ilish log',
                'verbose_name_plural': 'Ilish loglar',
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
