# Generated by Django 6.0 on 2026-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vishilka',
            options={'ordering': ['quantity', 'nomi'], 'verbose_name': 'Vishilka', 'verbose_name_plural': 'Vishilkalar'},
        ),
        migrations.RemoveField(
            model_name='ilishjarayonlog',
            name='natija',
        ),
        migrations.RemoveField(
            model_name='vishilka',
            name='turi',
        ),
        migrations.AddField(
            model_name='vishilka',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Masalan: 25 parlik vishilka uchun 25 kiriting', verbose_name='Par soni (bir vishilkada)'),
        ),
    ]
